package chapter_10_2;

public class MyExceptionTest {
	public static void main(String args[]){
		try{
			
		}catch(RuntimeException re){
			System.out.println("运行时异常");
		}
	}
}
